# Generated by Django 4.0.2 on 2022-03-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.course'),
        ),
        migrations.AddField(
            model_name='application',
            name='client_last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Familiya'),
        ),
    ]
